### ISSUE TITLE
Error when building apk with MacOS: "Container action is only supported on Linux"

### ISSUE THREAD

**Issue by cdiezsanchez-chwy** [skywall/universal-apk-builder#3]
I was doing some tests running our CI pipeline on MacOs and the APK build process (using his action) fails due to only being supported on Linux.

<img width="465" alt="Screenshot 2020-06-17 at 8 08 11 AM" src="https://user-images.githubusercontent.com/64597899/84896306-b86a7900-b071-11ea-940a-dbf05df049a3.png">

After digging into this, I think the source of the issue is running the action on a `Docker` image. They run on Linux as [pointed out on the documentation](https://help.github.com/en/actions/creating-actions/about-actions#types-of-actions)
More info on the topic [here](https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981) and [here](https://github.community/t/why-is-docker-not-installed-on-macos/17017).

**Comment by skywall** [comment]
Thanks, i'll look into it.

**Comment by skywall** [comment]
Hello @cdiezsanchez-chwy , support for MacOS means to rewrite a whole action into JavaScript which I don't want to do atm.
