### ISSUE TITLE
Facing issue due to github policy

### ISSUE THREAD

**Issue by ayan-biswas0412** [skywall/universal-apk-builder#5]
Error: Unable to process command '::set-env name=UNIVERSAL_APK_PATH::android/app/build/outputs/apk/release/universal.apk' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

@skywall  Please take care of it i am getting this error when try to use your action

**Comment by skywall** [comment]
@ayan-biswas0412 Hello, I have fixed the issue. Can you please try the new version (v1.0.1) and check if everything works ok for you?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Hello, I have fixed the issue. Can you please try the new version (v1.0.1) and check if everything works ok for you?

Yes it worked thank you
